#ifndef MSCONNECTOR_DIRECTIVES_H
#define MSCONNECTOR_DIRECTIVES_H

#ifdef __cplusplus
extern "C" {
#endif

#define MSCONNECTOR_DIRECTIVE_MODSECURITY "modsecurity"
#define MSCONNECTOR_DIRECTIVE_RULES "modsecurity_rules"
#define MSCONNECTOR_DIRECTIVE_RULES_FILE "modsecurity_rules_file"
#define MSCONNECTOR_DIRECTIVE_RULES_REMOTE "modsecurity_rules_remote"
#define MSCONNECTOR_DIRECTIVE_TRANSACTION_ID "modsecurity_transaction_id"
#define MSCONNECTOR_DIRECTIVE_TRANSACTION_ID_EXPR "modsecurity_transaction_id_expr"
#define MSCONNECTOR_DIRECTIVE_PHASE4_MODE "modsecurity_phase4_mode"
#define MSCONNECTOR_DIRECTIVE_PHASE4_CONTENT_TYPES_FILE "modsecurity_phase4_content_types_file"
#define MSCONNECTOR_DIRECTIVE_PHASE4_LOG "modsecurity_phase4_log"
#define MSCONNECTOR_DIRECTIVE_PHASE4_BODY_LIMIT "modsecurity_phase4_body_limit"
#define MSCONNECTOR_DIRECTIVE_REQUEST_BODY_LIMIT "modsecurity_request_body_limit"
#define MSCONNECTOR_DIRECTIVE_RESPONSE_BODY_LIMIT "modsecurity_response_body_limit"
#define MSCONNECTOR_DIRECTIVE_BODY_LIMIT_ACTION "modsecurity_body_limit_action"
#define MSCONNECTOR_DIRECTIVE_LATE_INTERVENTION_TIMEOUT "modsecurity_late_intervention_timeout"
#define MSCONNECTOR_DIRECTIVE_USE_ERROR_LOG "modsecurity_use_error_log"

#ifdef __cplusplus
}
#endif

#endif
