#ifndef MSCONNECTOR_OPTIONS_H
#define MSCONNECTOR_OPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

#define MSCONNECTOR_OPTION_ENABLE "enable"
#define MSCONNECTOR_OPTION_RULES_INLINE "rules-inline"
#define MSCONNECTOR_OPTION_RULES_FILE "rules-file"
#define MSCONNECTOR_OPTION_RULES_REMOTE "rules-remote"
#define MSCONNECTOR_OPTION_TRANSACTION_ID "transaction-id"
#define MSCONNECTOR_OPTION_USE_ERROR_LOG "use-error-log"
#define MSCONNECTOR_OPTION_PHASE4_MODE "phase4-mode"
#define MSCONNECTOR_OPTION_PHASE4_CONTENT_TYPES_FILE "phase4-content-types-file"
#define MSCONNECTOR_OPTION_PHASE4_LOG "phase4-log"
#define MSCONNECTOR_OPTION_PHASE4_BODY_LIMIT "phase4-body-limit"

enum msconnector_bool_option {
    MSCONNECTOR_BOOL_UNSET = -1,
    MSCONNECTOR_BOOL_OFF = 0,
    MSCONNECTOR_BOOL_ON = 1
};

enum msconnector_phase4_mode {
    MSCONNECTOR_PHASE4_MODE_UNSET = -1,
    MSCONNECTOR_PHASE4_MODE_MINIMAL = 0,
    MSCONNECTOR_PHASE4_MODE_SAFE = 1,
    MSCONNECTOR_PHASE4_MODE_STRICT = 2
};

#define MSCONNECTOR_DEFAULT_ENABLE MSCONNECTOR_BOOL_OFF
#define MSCONNECTOR_DEFAULT_USE_ERROR_LOG MSCONNECTOR_BOOL_ON
#define MSCONNECTOR_DEFAULT_PHASE4_MODE MSCONNECTOR_PHASE4_MODE_SAFE
#define MSCONNECTOR_DEFAULT_PHASE4_BODY_LIMIT 1048576

#define MSCONNECTOR_DEFAULT_PHASE4_CONTENT_TYPE_COUNT 6
#define MSCONNECTOR_DEFAULT_PHASE4_CONTENT_TYPE_TEXT_HTML "text/html"
#define MSCONNECTOR_DEFAULT_PHASE4_CONTENT_TYPE_TEXT_PLAIN "text/plain"
#define MSCONNECTOR_DEFAULT_PHASE4_CONTENT_TYPE_APPLICATION_JSON "application/json"
#define MSCONNECTOR_DEFAULT_PHASE4_CONTENT_TYPE_APPLICATION_XML "application/xml"
#define MSCONNECTOR_DEFAULT_PHASE4_CONTENT_TYPE_TEXT_XML "text/xml"
#define MSCONNECTOR_DEFAULT_PHASE4_CONTENT_TYPE_APPLICATION_XHTML_XML "application/xhtml+xml"

#ifdef __cplusplus
}
#endif

#endif
