from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "generate_repository_organization_inventory.py"
SPEC = importlib.util.spec_from_file_location("repository_organization_inventory_test", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
INVENTORY = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = INVENTORY
SPEC.loader.exec_module(INVENTORY)

OPEN_BRACE = "$" + "{"


class RepositoryOrganizationInventoryTest(unittest.TestCase):
    def test_language_keeps_english_and_german_suffix_classification(self) -> None:
        self.assertEqual(INVENTORY.language("README.de.md"), "de")
        self.assertEqual(INVENTORY.language("README.md"), "en")
        self.assertEqual(INVENTORY.language("README.txt"), "n/a")

    def test_variable_regex_preserves_supported_and_rejected_forms(self) -> None:
        cases = {
            "$FOO": ["$FOO"],
            OPEN_BRACE + "FOO}": [OPEN_BRACE + "FOO}"],
            "$(FOO)": ["$(FOO)"],
            "VAR=": ["VAR="],
            "ABC =": ["ABC ="],
            "BUILD_MODE:=": ["BUILD_MODE:="],
            "FEATURE+=": ["FEATURE+="],
            "$FOO}": ["$FOO}"],
            f"{OPEN_BRACE}FOO": [f"{OPEN_BRACE}FOO"],
            f"{OPEN_BRACE}FOO)": [f"{OPEN_BRACE}FOO"],
            "$FOO=": ["$FOO"],
            "$foo": [],
            "$(FOO": [],
            "AB=": [],
            "lower=": [],
            "ABC-=": [],
            "$": [],
        }

        for text, expected in cases.items():
            with self.subTest(text=text):
                self.assertEqual(INVENTORY.variable_matches(text), expected)

    def test_reference_regex_preserves_known_reference_boundaries(self) -> None:
        cases = {
            "ci/checks/foo.py": ["ci/checks/foo.py"],
            "docs/a-b.md": ["docs/a-b.md"],
            "reports/a.b/c": ["reports/a.b/c"],
            "examples/demo.yml": ["examples/demo.yml"],
            "make check-docs": ["make check-docs"],
            "make\tquick-check": ["make\tquick-check"],
            "cix/foo": [],
            "myci/foo": [],
            "CI/foo": [],
            "ci/": [],
            "documentation/a": [],
            "make": [],
            "make /": [],
        }

        for text, expected in cases.items():
            with self.subTest(text=text):
                self.assertEqual(INVENTORY.REFERENCE_RE.findall(text), expected)

    def test_category_preserves_precedence_and_fallback(self) -> None:
        cases = (
            ("docs/security-inventory-fixture.md", "Generated by the inventory script", "generated"),
            ("docs/security-plan-inventory-fixture.md", "", "historical"),
            ("docs/security-inventory-fixture.md", "", "security"),
            ("reports/evidence-inventory-fixture.md", "", "evidence"),
            ("docs/test-inventory-build-fixture.md", "", "testing"),
            ("docs/build-inventory-architecture-fixture.md", "", "build-guide"),
            ("docs/common-inventory-roadmap-fixture.md", "", "architecture"),
            ("docs/roadmap-inventory-fixture.md", "", "roadmap"),
            ("docs/connectors/inventory-fixture.md", "", "connector-guide"),
            ("docs/apache-inventory-fixture.md", "", "connector-guide"),
            ("README-inventory-fixture.de.md", "", "entry-point"),
            ("docs/inventory-guide-fixture.md", "", "current-guide"),
        )

        for path, text, expected in cases:
            with self.subTest(path=path, text=text):
                self.assertEqual(INVENTORY.category(path, text), expected)

    def test_proposed_destination_preserves_routes_and_fallbacks(self) -> None:
        framework_prefix = "modules/ModSecurity-test-Framework/"
        cases = (
            ("COMPILE_OPEN_CONNECTORS.md", False, "docs/build/compilers/overview.md"),
            ("COMPILE_GUIDE.de.md", False, "docs/build/compilers/guide.de.md"),
            ("ci/check-doc-inventory-fixture.py", False, "ci/checks/documentation/check-doc-inventory-fixture.py"),
            ("ci/check-lifecycle-inventory-fixture.py", False, "ci/checks/evidence/check-lifecycle-inventory-fixture.py"),
            ("ci/check-haproxy-inventory-fixture.py", False, "ci/checks/connectors/haproxy/check-haproxy-inventory-fixture.py"),
            ("ci/check-generic-inventory-fixture.py", False, "ci/checks/common/check-generic-inventory-fixture.py"),
            ("ci/prepare-inventory-fixture.py", False, "ci/provisioning/components/prepare-inventory-fixture.py"),
            ("ci/run-inventory-fixture.py", False, "ci/runtime/lifecycle/run-inventory-fixture.py"),
            ("ci/generate-inventory-fixture.py", False, "ci/evidence/reports/generate-inventory-fixture.py"),
            ("ci/inventory-helper-fixture.py", False, "ci/lib/inventory-helper-fixture.py"),
            ("reports/six-connector-inventory-fixture.md", False, "reports/current/core-completion.md"),
            ("reports/six-connector-inventory-fixture.de.md", False, "reports/current/core-completion.de.md"),
            ("reports/full-lifecycle-readiness-inventory-fixture.md", False, "reports/current/readiness.md"),
            ("reports/full-lifecycle-readiness-inventory-fixture.de.md", False, "reports/current/readiness.de.md"),
            ("reports/audit-inventory-fixture.md", False, "reports/audits/architecture-and-evidence.md"),
            ("reports/adoption-inventory-fixture.de.md", False, "reports/audits/architecture-and-evidence.de.md"),
            ("reports/inventory-notes-fixture.md", False, "remove"),
            ("docs/inventory-plan-fixture.md", False, "docs/inventory-plan-fixture.md"),
            (f"{framework_prefix}ci/check_evidence_inventory_fixture.py", True, f"{framework_prefix}ci/checks/evidence/check_evidence_inventory_fixture.py"),
            (f"{framework_prefix}ci/check_protocol_inventory_fixture.py", True, f"{framework_prefix}ci/checks/protocol/check_protocol_inventory_fixture.py"),
            (f"{framework_prefix}ci/check-doc-inventory-fixture.py", True, f"{framework_prefix}ci/checks/documentation/check-doc-inventory-fixture.py"),
            (f"{framework_prefix}ci/check-inventory-fixture.py", True, f"{framework_prefix}ci/checks/catalog/check-inventory-fixture.py"),
            (f"{framework_prefix}ci/check_inventory_fixture.py", True, f"{framework_prefix}ci/checks/catalog/check_inventory_fixture.py"),
            (f"{framework_prefix}ci/run-inventory-fixture.py", True, f"{framework_prefix}ci/runtime/run-inventory-fixture.py"),
            (f"{framework_prefix}ci/prepare-inventory-fixture.py", True, f"{framework_prefix}ci/provisioning/prepare-inventory-fixture.py"),
            (f"{framework_prefix}ci/generate-inventory-fixture.py", True, f"{framework_prefix}ci/reporting/generate-inventory-fixture.py"),
            (f"{framework_prefix}ci/inventory-helper-fixture.py", True, f"{framework_prefix}ci/lib/inventory-helper-fixture.py"),
            (f"{framework_prefix}ci/nested/inventory-helper-fixture.py", True, f"{framework_prefix}ci/nested/inventory-helper-fixture.py"),
            (f"{framework_prefix}docs/inventory-guide-fixture.md", True, f"{framework_prefix}docs/inventory-guide-fixture.md"),
        )

        for path, is_framework, expected in cases:
            with self.subTest(path=path, is_framework=is_framework):
                self.assertEqual(INVENTORY.proposed_destination(path, is_framework), expected)

    def test_framework_check_prefixes_keep_catalog_routing(self) -> None:
        framework_prefix = "modules/ModSecurity-test-Framework/ci/"

        self.assertEqual(
            INVENTORY.proposed_destination(f"{framework_prefix}check-smoke.py", True),
            f"{framework_prefix}checks/catalog/check-smoke.py",
        )
        self.assertEqual(
            INVENTORY.proposed_destination(f"{framework_prefix}check_smoke.py", True),
            f"{framework_prefix}checks/catalog/check_smoke.py",
        )
