#!/usr/bin/env python3
"""Create a temporary documentation-reorganization inventory and move plan.

This repository-maintenance tool reads tracked files only. Its audit outputs
use a private randomly named directory below ``${TMP_ROOT:-/tmp}`` so a
planning snapshot never becomes a competing versioned report or follows a
pre-created shared temporary path.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import tempfile
from collections import Counter, defaultdict
from datetime import UTC, datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRAMEWORK = ROOT / "modules" / "ModSecurity-test-Framework"
CONNECTORS = ("apache", "nginx", "haproxy", "envoy", "traefik", "lighttpd")
VARIABLE_REFERENCE_RE = re.compile(
    r"\$\{?[A-Z][A-Z0-9_]*\}?|\$\([A-Z][A-Z0-9_]*\)"
)
VARIABLE_ASSIGNMENT_RE = re.compile(r"\b[A-Z][A-Z0-9_]{2,}\s*[?:+]?=")
VARIABLE_PATTERNS = (VARIABLE_REFERENCE_RE, VARIABLE_ASSIGNMENT_RE)
PLACEHOLDER_RE = re.compile(
    r"(?:<[A-Za-z][A-Za-z0-9 _-]*>|\b(?:REPLACE_ME|CHANGE_ME)\b|\{\{[^}]+\}\}|\$\{\{[^}]+\}\})"
)
REFERENCE_RE = re.compile(r"\b(?:(?:ci|docs|reports|examples)/[\w./-]+|make\s+[\w.-]+)")
CATEGORY_PATH_TOKEN_RULES = (
    ("historical", ("archive", "histor", "poc", "open_items", "todo", "plan", "audit")),
    ("security", ("security",)),
    ("evidence", ("evidence", "lifecycle")),
    ("testing", ("test", "case", "matrix")),
    ("build-guide", ("compile", "build")),
    ("architecture", ("architecture", "common")),
    ("roadmap", ("roadmap",)),
)
PARENT_CI_CHECK_KEYWORD_DESTINATIONS = (
    (("doc", "bilingual", "generated-report"), "ci/checks/documentation"),
    (("lifecycle", "evidence", "first-byte", "no-crs", "six-connector", "runtime-root"), "ci/checks/evidence"),
)
PARENT_CI_CONNECTORS = ("apache", "nginx", "haproxy")
PARENT_CI_PREFIX_DESTINATIONS = (
    (("prepare-", "runtime-components", "with-runtime", "detect-c-standard"), "ci/provisioning/components"),
    (("run-", "resolve-", "write-", "collect-", "consume-", "sanitize-", "reserve-"), "ci/runtime/lifecycle"),
    (("generate-", "refresh-", "update-"), "ci/evidence/reports"),
)
FRAMEWORK_CI_SPECIAL_DESTINATIONS = (
    (("check_",), ("evidence",), "ci/checks/evidence"),
    (("check_",), ("protocol",), "ci/checks/protocol"),
    (("check-",), ("doc",), "ci/checks/documentation"),
)
FRAMEWORK_CI_PREFIX_DESTINATIONS = (
    (("check-", "check_"), "ci/checks/catalog"),
    (("run-", "no_crs", "protocol_client", "response_body"), "ci/runtime"),
    (("prepare-", "fetch-", "build-", "find-", "materialize-"), "ci/provisioning"),
    (("generate-", "write-", "summarize-", "update-"), "ci/reporting"),
)


def tracked_files(directory: Path) -> list[str]:
    command = ["git", "-C", str(directory), "ls-files"]
    return subprocess.check_output(command, text=True).splitlines()


def private_audit_root() -> Path:
    """Allocate a private audit directory without reusing a predictable name."""
    temporary_parent = Path(os.environ.get("TMP_ROOT") or tempfile.gettempdir())
    temporary_parent.mkdir(parents=True, exist_ok=True)
    return Path(
        tempfile.mkdtemp(prefix="modsecurity-doc-cleanup-", dir=temporary_parent)
    )


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def variable_matches(text: str) -> list[str]:
    """Return variable references and assignments in source order.

    The two small patterns avoid a single high-complexity expression.  Keep
    the leftmost match when a reference and an assignment overlap, matching
    the prior regular-expression scanner behavior for inputs such as
    ``$FOO=``.
    """
    matches = sorted(
        (match for pattern in VARIABLE_PATTERNS for match in pattern.finditer(text)),
        key=lambda match: (match.start(), -match.end()),
    )
    result: list[str] = []
    consumed_until = 0
    for match in matches:
        if match.start() < consumed_until:
            continue
        result.append(match.group())
        consumed_until = match.end()
    return result


def language(path: str) -> str:
    if path.endswith(".de.md"):
        return "de"
    if path.endswith(".md"):
        return "en"
    return "n/a"


def connector(path: str) -> str | None:
    lower = path.lower()
    return next((name for name in CONNECTORS if f"/{name}/" in lower or name in Path(lower).name), None)


def _is_generated_category(lower: str, text: str) -> bool:
    return "generated" in lower or ".generated." in lower or "generated by" in text.lower()


def _category_from_path(path: str, lower: str) -> str | None:
    for category_name, tokens in CATEGORY_PATH_TOKEN_RULES:
        if any(token in lower for token in tokens):
            return category_name
    if "/connectors/" in lower or connector(path):
        return "connector-guide"
    if Path(path).name.lower().startswith("readme"):
        return "entry-point"
    return None


def category(path: str, text: str) -> str:
    lower = path.lower()
    if _is_generated_category(lower, text):
        return "generated"
    return _category_from_path(path, lower) or "current-guide"


def _keyword_destination(
    lower: str,
    destinations: tuple[tuple[tuple[str, ...], str], ...],
) -> str | None:
    return next(
        (destination for keywords, destination in destinations if any(keyword in lower for keyword in keywords)),
        None,
    )


def _prefix_destination(
    lower: str,
    destinations: tuple[tuple[tuple[str, ...], str], ...],
    fallback: str,
) -> str:
    return next(
        (destination for prefixes, destination in destinations if lower.startswith(prefixes)),
        fallback,
    )


def _special_prefix_destination(lower: str) -> str | None:
    return next(
        (
            destination
            for prefixes, keywords, destination in FRAMEWORK_CI_SPECIAL_DESTINATIONS
            if lower.startswith(prefixes) and all(keyword in lower for keyword in keywords)
        ),
        None,
    )


def _parent_ci_destination(name: str) -> str:
    lower = name.lower()
    if lower.startswith("check-"):
        destination = _keyword_destination(lower, PARENT_CI_CHECK_KEYWORD_DESTINATIONS)
        if destination is not None:
            return f"{destination}/{name}"
        selected_connector = next((item for item in PARENT_CI_CONNECTORS if item in lower), None)
        if selected_connector is not None:
            return f"ci/checks/connectors/{selected_connector}/{name}"
        return f"ci/checks/common/{name}"
    destination = _prefix_destination(lower, PARENT_CI_PREFIX_DESTINATIONS, "ci/lib")
    return f"{destination}/{name}"


def _framework_ci_destination(prefix: str, name: str) -> str:
    lower = name.lower()
    special_destination = _special_prefix_destination(lower)
    destination = special_destination or _prefix_destination(lower, FRAMEWORK_CI_PREFIX_DESTINATIONS, "ci/lib")
    return f"{prefix}{destination}/{name}"


def _compiler_destination(name: str) -> str | None:
    if not name.startswith("COMPILE_") or not name.endswith(".md"):
        return None
    stem = name.removeprefix("COMPILE_").removesuffix(".md").lower()
    if stem.endswith(".de"):
        stem = stem.removesuffix(".de") + ".de"
    if stem == "open_connectors":
        stem = "overview"
    return f"docs/build/compilers/{stem}.md"


def _parent_report_destination(name: str) -> str:
    if "six-connector" in name:
        return "reports/current/core-completion.de.md" if name.endswith(".de.md") else "reports/current/core-completion.md"
    if "full-lifecycle-readiness" in name:
        return "reports/current/readiness.de.md" if name.endswith(".de.md") else "reports/current/readiness.md"
    if "audit" in name or "adoption" in name:
        return "reports/audits/architecture-and-evidence.de.md" if name.endswith(".de.md") else "reports/audits/architecture-and-evidence.md"
    return "remove"


def _parent_destination(local: str, name: str) -> str | None:
    compiler_destination = _compiler_destination(name)
    if compiler_destination is not None:
        return compiler_destination
    if local.startswith("ci/") and local.count("/") == 1:
        return _parent_ci_destination(name)
    if local.startswith("reports/") and local.count("/") == 1 and name.endswith(".md"):
        return _parent_report_destination(name)
    return None


def _framework_destination(prefix: str, local: str, name: str) -> str | None:
    if local.startswith("ci/") and local.count("/") == 1:
        return _framework_ci_destination(prefix, name)
    return None


def proposed_destination(path: str, is_framework: bool) -> str:
    prefix = "modules/ModSecurity-test-Framework/" if is_framework else ""
    local = path[len(prefix) :] if prefix else path
    name = Path(local).name
    destination = (
        _framework_destination(prefix, local, name)
        if is_framework
        else _parent_destination(local, name)
    )
    return destination if destination is not None else prefix + local


def action(path: str, destination: str, kind: str) -> str:
    if kind == "generated":
        return "generate"
    if path != destination:
        return "move"
    if path.endswith(".md") and kind == "historical":
        return "archive"
    return "keep"


def inventory_row(path: str, filesystem_path: Path, is_framework: bool, source_texts: dict[str, str]) -> dict[str, object]:
    text = read_text(filesystem_path)
    kind = category(path, text)
    destination = proposed_destination(path, is_framework)
    basename = Path(path).name
    referenced = sorted(
        source for source, source_text in source_texts.items() if source != path and (path in source_text or basename in source_text)
    )
    variables = sorted(set(variable_matches(text)))
    placeholders = sorted(set(PLACEHOLDER_RE.findall(text)))
    references = sorted(set(REFERENCE_RE.findall(text)))
    local_docs = bool(re.search(r"(?:variable|placeholder|configuration values|konfigurationsvariablen)", text, re.I))
    central_docs = ("docs/reference/variables" in text or "docs/reference/glossary" in text)
    missing: list[str] = []
    if variables and not local_docs:
        missing.append("variable explanations")
    if placeholders and not local_docs:
        missing.append("placeholder explanations")
    return {
        "path": path,
        "file_type": filesystem_path.suffix.removeprefix(".") or "extensionless",
        "language": language(path),
        "generated": kind == "generated",
        "historical": kind == "historical",
        "current": kind not in {"historical"},
        "connector": connector(path),
        "category": kind,
        "referenced_by": referenced,
        "proposed_destination": destination,
        "action": action(path, destination, kind),
        "variables_found": variables,
        "placeholders_found": placeholders,
        "references_found": references,
        "documented_locally": local_docs,
        "documented_centrally": central_docs,
        "missing_documentation": missing,
    }


def plan(rows: list[dict[str, object]], german: bool) -> str:
    counts = Counter(str(row["action"]) for row in rows)
    scopes = Counter("Framework" if str(row["path"]).startswith("modules/") else "Superproject" for row in rows)
    title = "Repository organization plan" if not german else "Plan für die Repository-Organisation"
    language_line = "**Language:** English | [Deutsch](repository-organization-plan.de.md)" if not german else "**Sprache:** [English](repository-organization-plan.md) | Deutsch"
    intro = (
        "This is the pre-reorganization plan generated from tracked files. It records proposed moves before implementation; it is not a claim that a historical report is current."
        if not german
        else "Dies ist der aus versionierten Dateien erzeugte Vor-Reorganisationsplan. Er dokumentiert vorgeschlagene Verschiebungen vor der Umsetzung und macht keine historischen Berichte zu aktuellen Aussagen."
    )
    labels = ("Files", "Proposed actions", "Next steps") if not german else ("Dateien", "Vorgeschlagene Aktionen", "Nächste Schritte")
    steps = (
        ["Move tracked files with `git mv`.", "Repair references in code, Makefiles, workflows, tests, and documentation.", "Regenerate generated reports from their source of truth.", "Validate links, language partners, variables, and the six-connector core."]
        if not german
        else ["Versionierte Dateien mit `git mv` verschieben.", "Referenzen in Code, Makefiles, Workflows, Tests und Dokumentation reparieren.", "Generierte Berichte über ihre Source of Truth neu erzeugen.", "Links, Sprachpartner, Variablen und den Sechs-Connector-Kern validieren."]
    )
    lines = [f"# {title}", "", language_line, "", intro, "", f"## {labels[0]}", "", "| Scope | Count |", "| --- | ---: |"]
    lines.extend(f"| {scope} | {count} |" for scope, count in sorted(scopes.items()))
    lines.extend(["", f"## {labels[1]}", "", "| Action | Count |", "| --- | ---: |"])
    lines.extend(f"| `{name}` | {count} |" for name, count in sorted(counts.items()))
    lines.extend(["", f"## {labels[2]}", ""])
    lines.extend(f"{index}. {step}" for index, step in enumerate(steps, 1))
    lines.extend(["", "The machine-readable inventory is [repository-organization-inventory.json](repository-organization-inventory.json)." if not german else "Das maschinenlesbare Inventar steht in [repository-organization-inventory.json](repository-organization-inventory.json).", ""])
    return "\n".join(lines)


def main() -> None:
    root_paths = tracked_files(ROOT)
    framework_paths = tracked_files(FRAMEWORK)
    prefixed_framework = [f"modules/ModSecurity-test-Framework/{path}" for path in framework_paths]
    all_paths = root_paths + prefixed_framework
    source_texts: dict[str, str] = {}
    for path in all_paths:
        physical = ROOT / path
        source_texts[path] = read_text(physical)
    rows = [
        inventory_row(path, ROOT / path, path.startswith("modules/ModSecurity-test-Framework/"), source_texts)
        for path in all_paths
        if path.startswith(("ci/", "docs/", "examples/", "reports/", "modules/ModSecurity-test-Framework/"))
        or ("/" not in path and path.endswith(".md"))
    ]
    payload = {
        "inventory_stage": "pre-reorganization",
        "generated_at_utc": datetime.now(UTC).replace(microsecond=0).isoformat(),
        "scope": "tracked CI, documentation, examples, reports, root Markdown, and Framework files",
        "allowed_actions": ["keep", "move", "merge", "rewrite", "archive", "generate", "remove_duplicate"],
        "files": rows,
    }
    audit_root = private_audit_root()
    (audit_root / "repository-organization-inventory.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (audit_root / "repository-organization-plan.md").write_text(plan(rows, german=False), encoding="utf-8")
    (audit_root / "repository-organization-plan.de.md").write_text(plan(rows, german=True), encoding="utf-8")
    print(f"repository-organization-inventory: wrote temporary inventory: {audit_root}")


if __name__ == "__main__":
    main()
