#!/usr/bin/env python3
"""Create a temporary documentation-reorganization inventory and move plan.

This repository-maintenance tool reads tracked files only. Its audit outputs
belong below ``${TMP_ROOT:-/tmp}/modsecurity-doc-cleanup`` so a planning
snapshot never becomes a competing versioned report.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from collections import Counter, defaultdict
from datetime import UTC, datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRAMEWORK = ROOT / "modules" / "ModSecurity-test-Framework"
AUDIT_ROOT = Path(os.environ.get("TMP_ROOT", "/tmp")) / "modsecurity-doc-cleanup"
CONNECTORS = ("apache", "nginx", "haproxy", "envoy", "traefik", "lighttpd")
VARIABLE_RE = re.compile(
    r"(?:\$\{?[A-Z][A-Z0-9_]*\}?|\$\([A-Z][A-Z0-9_]*\)|\b[A-Z][A-Z0-9_]{2,}\s*(?:\?|:|\+)?=)"
)
PLACEHOLDER_RE = re.compile(
    r"(?:<[A-Za-z][A-Za-z0-9 _-]*>|\b(?:REPLACE_ME|CHANGE_ME)\b|\{\{[^}]+\}\}|\$\{\{[^}]+\}\})"
)
REFERENCE_RE = re.compile(r"(?:\bci/[\w./-]+|\bdocs/[\w./-]+|\breports/[\w./-]+|\bexamples/[\w./-]+|\bmake\s+[\w.-]+)")


def tracked_files(directory: Path) -> list[str]:
    command = ["git", "-C", str(directory), "ls-files"]
    return subprocess.check_output(command, text=True).splitlines()


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def language(path: str) -> str:
    if path.endswith(".de.md"):
        return "de"
    if path.endswith(".md"):
        return "en"
    return "n/a"


def connector(path: str) -> str | None:
    lower = path.lower()
    return next((name for name in CONNECTORS if f"/{name}/" in lower or name in Path(lower).name), None)


def category(path: str, text: str) -> str:
    lower = path.lower()
    if "generated" in lower or ".generated." in lower or "generated by" in text.lower():
        return "generated"
    if any(token in lower for token in ("archive", "histor", "poc", "open_items", "todo", "plan", "audit")):
        return "historical"
    if "security" in lower:
        return "security"
    if "evidence" in lower or "lifecycle" in lower:
        return "evidence"
    if "test" in lower or "case" in lower or "matrix" in lower:
        return "testing"
    if "compile" in lower or "build" in lower:
        return "build-guide"
    if "architecture" in lower or "common" in lower:
        return "architecture"
    if "roadmap" in lower:
        return "roadmap"
    if "/connectors/" in lower or connector(path):
        return "connector-guide"
    if Path(path).name.lower().startswith("readme"):
        return "entry-point"
    return "current-guide"


def proposed_destination(path: str, is_framework: bool) -> str:
    prefix = "modules/ModSecurity-test-Framework/" if is_framework else ""
    local = path[len(prefix) :] if prefix else path
    name = Path(local).name
    if not is_framework and name.startswith("COMPILE_") and name.endswith(".md"):
        stem = name.removeprefix("COMPILE_").removesuffix(".md").lower()
        if stem.endswith(".de"):
            stem = stem.removesuffix(".de") + ".de"
        if stem == "open_connectors":
            stem = "overview"
        return f"docs/build/compilers/{stem}.md"
    if not is_framework and local.startswith("ci/") and local.count("/") == 1:
        lower = name.lower()
        if lower.startswith("check-") and any(key in lower for key in ("doc", "bilingual", "generated-report")):
            return f"ci/checks/documentation/{name}"
        if lower.startswith("check-") and any(key in lower for key in ("lifecycle", "evidence", "first-byte", "no-crs", "six-connector", "runtime-root")):
            return f"ci/checks/evidence/{name}"
        if lower.startswith("check-") and any(key in lower for key in ("apache", "nginx", "haproxy")):
            selected = next(item for item in ("apache", "nginx", "haproxy") if item in lower)
            return f"ci/checks/connectors/{selected}/{name}"
        if lower.startswith("check-"):
            return f"ci/checks/common/{name}"
        if lower.startswith(("prepare-", "runtime-components", "with-runtime", "detect-c-standard")):
            return f"ci/provisioning/components/{name}"
        if lower.startswith(("run-", "resolve-", "write-", "collect-", "consume-", "sanitize-", "reserve-")):
            return f"ci/runtime/lifecycle/{name}"
        if lower.startswith(("generate-", "refresh-", "update-")):
            return f"ci/evidence/reports/{name}"
        return f"ci/lib/{name}"
    if is_framework and local.startswith("ci/") and local.count("/") == 1:
        lower = name.lower()
        if lower.startswith("check_") and "evidence" in lower:
            return f"{prefix}ci/checks/evidence/{name}"
        if lower.startswith("check_") and "protocol" in lower:
            return f"{prefix}ci/checks/protocol/{name}"
        if lower.startswith("check-") and "doc" in lower:
            return f"{prefix}ci/checks/documentation/{name}"
        if lower.startswith("check-") or lower.startswith("check_"):
            return f"{prefix}ci/checks/catalog/{name}"
        if lower.startswith(("run-", "no_crs", "protocol_client", "response_body")):
            return f"{prefix}ci/runtime/{name}"
        if lower.startswith(("prepare-", "fetch-", "build-", "find-", "materialize-")):
            return f"{prefix}ci/provisioning/{name}"
        if lower.startswith(("generate-", "write-", "summarize-", "update-")):
            return f"{prefix}ci/reporting/{name}"
        return f"{prefix}ci/lib/{name}"
    if not is_framework and local.startswith("reports/") and local.count("/") == 1 and name.endswith(".md"):
        if "six-connector" in name:
            return "reports/current/core-completion.de.md" if name.endswith(".de.md") else "reports/current/core-completion.md"
        if "full-lifecycle-readiness" in name:
            return "reports/current/readiness.de.md" if name.endswith(".de.md") else "reports/current/readiness.md"
        if "audit" in name or "adoption" in name:
            return "reports/audits/architecture-and-evidence.de.md" if name.endswith(".de.md") else "reports/audits/architecture-and-evidence.md"
        return "remove"
    return prefix + local


def action(path: str, destination: str, kind: str) -> str:
    if kind == "generated":
        return "generate"
    if path != destination:
        return "move"
    if path.endswith(".md") and kind == "historical":
        return "archive"
    return "keep"


def inventory_row(path: str, filesystem_path: Path, is_framework: bool, source_texts: dict[str, str]) -> dict[str, object]:
    text = read_text(filesystem_path)
    kind = category(path, text)
    destination = proposed_destination(path, is_framework)
    basename = Path(path).name
    referenced = sorted(
        source for source, source_text in source_texts.items() if source != path and (path in source_text or basename in source_text)
    )
    variables = sorted(set(VARIABLE_RE.findall(text)))
    placeholders = sorted(set(PLACEHOLDER_RE.findall(text)))
    references = sorted(set(REFERENCE_RE.findall(text)))
    local_docs = bool(re.search(r"(?:variable|placeholder|configuration values|konfigurationsvariablen)", text, re.I))
    central_docs = ("docs/reference/variables" in text or "docs/reference/glossary" in text)
    missing: list[str] = []
    if variables and not local_docs:
        missing.append("variable explanations")
    if placeholders and not local_docs:
        missing.append("placeholder explanations")
    return {
        "path": path,
        "file_type": filesystem_path.suffix.removeprefix(".") or "extensionless",
        "language": language(path),
        "generated": kind == "generated",
        "historical": kind == "historical",
        "current": kind not in {"historical"},
        "connector": connector(path),
        "category": kind,
        "referenced_by": referenced,
        "proposed_destination": destination,
        "action": action(path, destination, kind),
        "variables_found": variables,
        "placeholders_found": placeholders,
        "references_found": references,
        "documented_locally": local_docs,
        "documented_centrally": central_docs,
        "missing_documentation": missing,
    }


def plan(rows: list[dict[str, object]], german: bool) -> str:
    counts = Counter(str(row["action"]) for row in rows)
    scopes = Counter("Framework" if str(row["path"]).startswith("modules/") else "Superproject" for row in rows)
    title = "Repository organization plan" if not german else "Plan für die Repository-Organisation"
    language_line = "**Language:** English | [Deutsch](repository-organization-plan.de.md)" if not german else "**Sprache:** [English](repository-organization-plan.md) | Deutsch"
    intro = (
        "This is the pre-reorganization plan generated from tracked files. It records proposed moves before implementation; it is not a claim that a historical report is current."
        if not german
        else "Dies ist der aus versionierten Dateien erzeugte Vor-Reorganisationsplan. Er dokumentiert vorgeschlagene Verschiebungen vor der Umsetzung und macht keine historischen Berichte zu aktuellen Aussagen."
    )
    labels = ("Files", "Proposed actions", "Next steps") if not german else ("Dateien", "Vorgeschlagene Aktionen", "Nächste Schritte")
    steps = (
        ["Move tracked files with `git mv`.", "Repair references in code, Makefiles, workflows, tests, and documentation.", "Regenerate generated reports from their source of truth.", "Validate links, language partners, variables, and the six-connector core."]
        if not german
        else ["Versionierte Dateien mit `git mv` verschieben.", "Referenzen in Code, Makefiles, Workflows, Tests und Dokumentation reparieren.", "Generierte Berichte über ihre Source of Truth neu erzeugen.", "Links, Sprachpartner, Variablen und den Sechs-Connector-Kern validieren."]
    )
    lines = [f"# {title}", "", language_line, "", intro, "", f"## {labels[0]}", "", "| Scope | Count |", "| --- | ---: |"]
    lines.extend(f"| {scope} | {count} |" for scope, count in sorted(scopes.items()))
    lines.extend(["", f"## {labels[1]}", "", "| Action | Count |", "| --- | ---: |"])
    lines.extend(f"| `{name}` | {count} |" for name, count in sorted(counts.items()))
    lines.extend(["", f"## {labels[2]}", ""])
    lines.extend(f"{index}. {step}" for index, step in enumerate(steps, 1))
    lines.extend(["", "The machine-readable inventory is [repository-organization-inventory.json](repository-organization-inventory.json)." if not german else "Das maschinenlesbare Inventar steht in [repository-organization-inventory.json](repository-organization-inventory.json).", ""])
    return "\n".join(lines)


def main() -> None:
    root_paths = tracked_files(ROOT)
    framework_paths = tracked_files(FRAMEWORK)
    prefixed_framework = [f"modules/ModSecurity-test-Framework/{path}" for path in framework_paths]
    all_paths = root_paths + prefixed_framework
    source_texts: dict[str, str] = {}
    for path in all_paths:
        physical = ROOT / path
        source_texts[path] = read_text(physical)
    rows = [
        inventory_row(path, ROOT / path, path.startswith("modules/ModSecurity-test-Framework/"), source_texts)
        for path in all_paths
        if path.startswith(("ci/", "docs/", "examples/", "reports/", "modules/ModSecurity-test-Framework/"))
        or ("/" not in path and path.endswith(".md"))
    ]
    payload = {
        "inventory_stage": "pre-reorganization",
        "generated_at_utc": datetime.now(UTC).replace(microsecond=0).isoformat(),
        "scope": "tracked CI, documentation, examples, reports, root Markdown, and Framework files",
        "allowed_actions": ["keep", "move", "merge", "rewrite", "archive", "generate", "remove_duplicate"],
        "files": rows,
    }
    AUDIT_ROOT.mkdir(parents=True, exist_ok=True)
    (AUDIT_ROOT / "repository-organization-inventory.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (AUDIT_ROOT / "repository-organization-plan.md").write_text(plan(rows, german=False), encoding="utf-8")
    (AUDIT_ROOT / "repository-organization-plan.de.md").write_text(plan(rows, german=True), encoding="utf-8")


if __name__ == "__main__":
    main()
