#!/bin/sh
set -eu

CONNECTOR_ROOT="${CONNECTOR_ROOT:-$(CDPATH= cd "$(dirname "$0")/.." && pwd)}"
FRAMEWORK_ROOT="${FRAMEWORK_ROOT:-$CONNECTOR_ROOT/modules/ModSecurity-test-Framework}"
PYTHON="${PYTHON:-python3}"
DEFAULT_STATE_HOME="${DEFAULT_STATE_HOME:-${XDG_STATE_HOME:-${HOME:-/tmp}/.local/state}}"
BUILD_ROOT="${BUILD_ROOT:-$DEFAULT_STATE_HOME/ModSecurity-conector-build}"
TMP_ROOT="${TMP_ROOT:-$BUILD_ROOT/tmp}"
LOG_ROOT="${LOG_ROOT:-$BUILD_ROOT/logs}"
MRTS_NATIVE_ROOT="${MRTS_NATIVE_ROOT:-$BUILD_ROOT/mrts-native}"

if [ -z "${CONNECTOR_COMPONENT_CACHE:-}" ]; then
    if [ -d /src ] && [ -w /src ]; then
        CONNECTOR_COMPONENT_CACHE=/src/ModSecurity-conector-cache
    else
        CONNECTOR_COMPONENT_CACHE="${XDG_CACHE_HOME:-${HOME:-/tmp}/.cache}/ModSecurity-conector"
    fi
fi

export CONNECTOR_ROOT FRAMEWORK_ROOT BUILD_ROOT TMP_ROOT LOG_ROOT MRTS_NATIVE_ROOT CONNECTOR_COMPONENT_CACHE

REPO_ROOT="$CONNECTOR_ROOT"
. "$FRAMEWORK_ROOT/ci/common.sh"

export MODSECURITY_REPO_URL MODSECURITY_GIT_REF MODSECURITY_V3_GIT_URL MODSECURITY_V3_GIT_REF
export MODSECURITY_APACHE_GIT_URL MODSECURITY_APACHE_GIT_REF MODSECURITY_NGINX_GIT_URL MODSECURITY_NGINX_GIT_REF
export CRS_REPO_URL CRS_GIT_REF
export HTTPD_VERSION HTTPD_SOURCE_URL HTTPD_SHA256 HTTPD_SHA256_URL
export APR_VERSION APR_SOURCE_URL APR_SHA256 APR_SHA256_URL
export APR_UTIL_VERSION APR_UTIL_SOURCE_URL APR_UTIL_SHA256 APR_UTIL_SHA256_URL
export PCRE2_VERSION PCRE2_SOURCE_URL PCRE2_SHA256 PCRE2_SHA256_URL
export NGINX_SOURCE_MODE NGINX_SOURCE_REPO_URL NGINX_GITHUB_REPO NGINX_RELEASE_TAG NGINX_SOURCE_GIT_REF NGINX_SHA256
export HAPROXY_VERSION HAPROXY_SOURCE_URL HAPROXY_SHA256_URL HAPROXY_SHA256
export EXPAT_GIT_URL EXPAT_PROMPT_EXPECTED_LATEST EXPAT_PREFIX EXPAT_BUILD_DIR

assert_safe_runtime_path "$BUILD_ROOT" BUILD_ROOT || exit 77
assert_safe_runtime_path "$TMP_ROOT" TMP_ROOT || exit 77
assert_safe_runtime_path "$LOG_ROOT" LOG_ROOT || exit 77
assert_safe_runtime_path "$MRTS_NATIVE_ROOT" MRTS_NATIVE_ROOT || exit 77
assert_safe_runtime_path "$CONNECTOR_COMPONENT_CACHE" CONNECTOR_COMPONENT_CACHE || exit 77
assert_not_system_path_for_write "$CONNECTOR_ROOT/reports/testing/generated" runtime_component_report_dir || exit 77

mkdir -p "$CONNECTOR_COMPONENT_CACHE" "$MRTS_NATIVE_ROOT" "$CONNECTOR_ROOT/reports/testing/generated"

"$PYTHON" "$CONNECTOR_ROOT/ci/prepare-runtime-components.py" \
    --connector-root "$CONNECTOR_ROOT" \
    --framework-root "$FRAMEWORK_ROOT" \
    --cache-root "$CONNECTOR_COMPONENT_CACHE" \
    --output-root "$CONNECTOR_ROOT" \
    --build-root "$BUILD_ROOT" \
    --native-root "$MRTS_NATIVE_ROOT"
