#!/bin/sh
set -eu

CONNECTOR_ROOT="${CONNECTOR_ROOT:-$(CDPATH= cd "$(dirname "$0")/.." && pwd)}"
FRAMEWORK_ROOT="${FRAMEWORK_ROOT:-$CONNECTOR_ROOT/modules/ModSecurity-test-Framework}"
VERIFIED_RUN_ROOT="${VERIFIED_RUN_ROOT:-${RUNNER_TEMP:-${TMPDIR:-/var/tmp}}/ModSecurity-conector-verified}"
VERIFIED_BUILD_ROOT="${VERIFIED_BUILD_ROOT:-$VERIFIED_RUN_ROOT/build}"
VERIFIED_COMPONENT_CACHE="${VERIFIED_COMPONENT_CACHE:-$VERIFIED_RUN_ROOT/component-cache}"
BUILD_ROOT="${BUILD_ROOT:-$VERIFIED_BUILD_ROOT}"

if [ -z "${CONNECTOR_COMPONENT_CACHE:-}" ]; then
    CONNECTOR_COMPONENT_CACHE="$VERIFIED_COMPONENT_CACHE"
fi
export CONNECTOR_ROOT FRAMEWORK_ROOT BUILD_ROOT CONNECTOR_COMPONENT_CACHE

if [ "${SKIP_RUNTIME_COMPONENT_PREPARE:-0}" != "1" ]; then
    sh "$CONNECTOR_ROOT/ci/prepare-runtime-components.sh"
fi
SKIP_RUNTIME_COMPONENT_PREPARE=1
export SKIP_RUNTIME_COMPONENT_PREPARE

runtime_env="$CONNECTOR_COMPONENT_CACHE/runtime-env.sh"
if [ -f "$runtime_env" ]; then
    # shellcheck disable=SC1090
    . "$runtime_env"
fi

exec "$@"
